gestion-condominios/routes/web.php
<?php

Route::get('/', function () {
    $towers = \App\Tower::count();
    return view('welcome', compact('towers'));
});

/*Route::get('test', function () {
  //return \App\Tower::with('apartments')->get();
});*/

/*Route::get('/profile', function () {
    return view('profile');
});

Route::get('/users/1', function () {
    return [
        'id' => 1,
        'name' => 'abalozz',
        'email' => 'abalozz@example.com',
    ];
});*/


Route::get('/select', 'HomeController@select');
Route::post('/select', ['as' => 'auth.select', 'uses' => 'HomeController@select_store'] );

Route::middleware(['auth'])->group(function () {

  Route::get('routeHome', function(){
		return redirect()->action('HomeController@index');
	})->name('routeHome');

  Route::get('admin/config/towers', ['as' => 'configTowersInitial', 'uses' => 'AdminConfigInitialController@index']);
  Route::post('registerTowers', ['as' => 'registerTowers', 'uses' => 'AdminConfigInitialController@storeTowers']);
  Route::get('admin/config/apartment-admin', ['as' => 'apartAdmin', 'uses' => 'AdminConfigInitialController@apartAdmin']);
  Route::post('registerApartAdmin', ['as' => 'registerApartAdmin', 'uses' => 'AdminConfigInitialController@registerApartAdmin']);

  Route::get('admin/config/payment-deadline-config', ['as' => 'config.initialPaymentDeadline', 'uses' => 'AdminConfigInitialController@initialPaymentDeadline']);

  Route::post('admin/payment-deadline-config/store', ['as' => 'config.storeMoorInterestConfigurationInitial', 'uses' => 'AdminConfigInitialController@storeMoorInterestConfigurationInitial']);

  Route::patch('admin/notifications/{id}', ['as' => 'notifications.read', 'uses' => 'NotificationsController@read']);
  Route::resource('admin/notifications', 'NotificationsController');


Route::name('admin.')->group(function () {
    Route::get('config/payment-deadline/config', ['as' => 'config.paymentDeadline', 'uses' => 'AdminConfigInitialController@paymentDeadline']);
    Route::post('config/payment-deadline/store', ['as' => 'config.storeMoorInterestConfiguration', 'uses' => 'AdminConfigInitialController@storeMoorInterestConfiguration']);

    Route::get('config/payment-deadline', ['as' => 'config.indexPayConfiguration', 'uses' => 'ArrearsInterestsController@index']);
    Route::get('config/payment-deadline/edit', ['as' => 'config.editPaymentDeadlineConfiguration', 'uses' => 'ArrearsInterestsController@edit']);
    Route::post('config/payment-deadline/update', ['as' => 'config.updatePaymentDeadlineConfiguration', 'uses' => 'AdminConfigInitialController@updatePaymentDeadline']);


    Route::resource('admin/towers', 'TowersController', ['except' => ['show']]);
    Route::get('admin/admins/type', ['as' => 'typeAdmin', 'uses' => 'AdminsController@type']);
    Route::get('admin/admins/extern', ['as' => 'externAdmin', 'uses' => 'AdminsController@extern']);
    Route::get('admin/admins/intern', ['as' => 'internAdmin', 'uses' => 'AdminsController@intern']);
    Route::resource('admin/admins', 'AdminsController', ['except' => ['show', 'create']]);
    Route::resource('admin/common-areas', 'CommonAreasController', ['except' => ['show']]);
    Route::match(['get', 'post'],'admin/apartments/apart-by-floor', 'ApartmentsController@createByfloor')->name('apartByFloor');
    Route::resource('admin/apartments', 'ApartmentsController', ['except' => ['show']]);
    Route::resource('admin/owners', 'OwnersController');
    Route::resource('admin/expenses', 'ExpenseController');
    Route::resource('admin/invoices', 'InvoiceController');
    Route::resource('admin/billing-notices', 'BillingNoticeController');
    Route::resource('admin/banks', 'BankController', ['except' => ['show']]);
    Route::resource('admin/banks-condominium', 'BankCondominiumController', ['except' => ['show']]);
    Route::resource('admin/ways-to-pay', 'WaysToPayController', ['except' => ['show']]);
    Route::resource('admin/news', 'NoticeController');
    Route::resource('admin/categories', 'CategoryController', ['except' => ['show']]);
    Route::get('admin/payments/confirm/{id}', ['as' => 'payments.confirm', 'uses' => 'PaymentController@confirm']);
    Route::get('admin/payments/unconfirmed', ['as' => 'payments.unconfirmed', 'uses' => 'PaymentController@unconfirmed']);
    Route::get('admin/payments/create/owner', ['as' => 'payments.createOwner', 'uses' => 'PaymentController@create_owner']);
    Route::post('admin/payments/create/', ['as' => 'payments.create', 'uses' => 'PaymentController@create']);
    Route::resource('admin/payments', 'PaymentController');
    Route::resource('admin/banks-condominium', 'BanksCondominiumController');
    Route::get('admin/statistics/date-range', ['as' => 'statistics.dateRange', 'uses' => 'StatisticsController@date_range']);
    Route::get('admin/statistics/type-expense', ['as' => 'statistics.typeExpense', 'uses' => 'StatisticsController@typeExpense']);
    Route::post('admin/statistics/graphic-expense', ['as' => 'statistics.graphicExpense', 'uses' => 'StatisticsController@graphicExpense']);
    Route::post('admin/statistics/graphic-range', ['as' => 'statistics.graphicRange', 'uses' => 'StatisticsController@graphicRange']);
    Route::resource('admin/statistics', 'StatisticsController');
    Route::get('admin/defaulters', ['as' => 'defaulters.index', 'uses' => 'DefaultersController@index']);
});

Route::name('owners.')->group(function ()
{
  Route::get('owners/', ['as' => 'owners.home', 'uses' => 'OwnersController@home']);
  Route::get('owners/edit-info', ['as' => 'owners.editInfo', 'uses' => 'OwnersController@editInfo']);
  Route::post('owners/store-info', ['as' => 'owners.storeInfo', 'uses' => 'OwnersController@storeInfo']);

  Route::get('owners/properties', ['as' => 'owners.properties', 'uses' => 'OwnersController@properties']);

  Route::get('owners/billing-notices/', ['as' => 'billing-notices.list', 'uses' => 'BillingNoticeController@list']);
  Route::get('owners/billing-notices/{id}/{apart}', ['as' => 'billing-notices.showFromOwner', 'uses' => 'BillingNoticeController@showFromOwner']);
  Route::get('owners/download-condo-receipt/{id}/{apart}', ['as' => 'pdf.condoReceipt', 'uses' => 'BillingNoticeController@pdfCondoReceipt']);

  Route::get('owners/billboard', ['as' => 'billboard.index', 'uses' => 'NoticeController@index_owner']);
  Route::get('owners/billboard/{id}', ['as' => 'billboard.show', 'uses' => 'NoticeController@show_owner']);

  Route::get('owners/payments', ['as' => 'payments.index', 'uses' => 'PaymentController@index_owner']);
  Route::post('owners/payments/store', ['as' => 'payments.store', 'uses' => 'PaymentController@store_owner']);
  Route::get('owners/payments/history', ['as' => 'payments.history', 'uses' => 'PaymentController@history_pays']);


});

});

gestion-condominios/resources/views/admin/admins/editExtern.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
	 <div class="row">
      <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Editar Administrador Externo</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{ route('admin.admins.update', $admin->id) }}" method="POST">
              {!! csrf_field() !!}
              {!! method_field('PUT') !!}
              <div class="box-body">
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="name">Nombre</label>
                      <input type="text" class="form-control" name="name" id="name" value="{{ $admin->name or old('name') }}" placeholder="Nombre">
                      <div class="errors">
                        {{ $errors->first('name') }}
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="last_name">Apellido</label>
                      <input type="text" class="form-control" name="last_name" id="last_name" value="{{ $admin->last_name or old('last_name') }}" placeholder="Apellido">
                        <div class="errors">
                          {{ $errors->first('last_name') }}
                        </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="ci">Cédula <small><i>(sólo números)</i></small></label>
                      <input type="text" class="form-control" name="ci" id="ci" value="{{ $admin->ci or old('ci') }}" placeholder="Cédula">
                      <div class="errors">
                        {{ $errors->first('ci') }}
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="birth">Fecha de Nacimiento</label>
                      <input type="text" class="form-control datepicker" name="birth" id="birth" value="{{ $admin->birth_formated or old('birth') }}" placeholder="dd-mm-yyyy">
                      <div class="errors">
                        {{ $errors->first('birth') }}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="email">Correo Electrónico</label>
                      <input type="text" class="form-control" name="email" id="email" value="{{ $admin->email or old('email') }}" placeholder="email@example.com">
                      <div class="errors">
                        {{ $errors->first('email') }}
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="phone">Teléfono</label>
                      <input type="text" class="form-control" name="number" id="phone" value="{{ $admin->number or old('number') }}" placeholder="0123-45678900">
                      <div class="errors">
                        {{ $errors->first('number') }}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="col-md-6">
                      <label for="role">Tipo de Administrador</label>
                      <br><br>
                      <div class="form-group">
                          @foreach ($roles as $id => $name)
                          <label>
                            <input type="checkbox"
                            value="{{ $id }}"
                            {{ $user->roles->pluck('id')->contains($id) ? 'checked' : '' }}
                            name="roles[]">
                            {{ $name }} <br>
                          </label>
                        @endforeach
                        <div class="errors">
                          {!! $errors->first('roles', '<span class=error>:message</span>') !!}
                        </div>
                    </div>
                  </div>
                  </div>
                </div>
                <hr>
                <input type="hidden" name="extern" value="1">
                <div class="box-footer">
                <a href="{{ URL::previous() }}">
                  <button type="button" class="btn btn-warning"><i class="fa fa-reply"></i> Atrás</button>
                </a>
                <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Guardar Información</button>
              </div>
            </form>
          </div>
   </div>
	</div>

@endsection

gestion-condominios/resources/views/admin/admins/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
	 <div class="row">
    <div class="col-md-9"></div>
    <div class="col-md-3">
      <a href="{{ route('admin.typeAdmin') }}">
        <button class="btn btn-success btn-block" title="Agregar Administrador"><i class="fa fa-plus"></i> Agregar Administrador</button>
      </a>
    </div>
   </div>
   <br>
   <div class="row">
      <div class="box box-info">
            <div class="box-header">
              <h3 class="box-title">Lista de Administradores</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Correo</th>
                  {{-- <th>Rol</th> --}}
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                  @foreach($admins as $admin)
                    <tr>
                        <td>{{ $admin->name }} {{ $admin->last_name }}</td>
                        <td>{{ $admin->email }}</td>
                        {{-- <td></td> --}}
                      <td>
                        {!!link_to_route('admin.admins.edit', $title = ' Editar',
                                                    $parameters = ['id' => Crypt::encrypt($admin->id)],
                                                    $attributes = ['class'=>'btn btn-warning fa fa-edit']);!!}
                        @if(Auth::user()->id != $admin->id)
                        <form style="display:inline" action="{{ route('admin.admins.destroy', $admin->id) }}" method="POST">
                          {!! csrf_field() !!}
                          {!! method_field('DELETE') !!}
                          <button class="btn btn-danger" type="submit"><span class="fa fa-trash" title="Eliminar"></span> Eliminar</button>
                        </form>
                        @endif
                      </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Nombre</th>
                  <th>Correo</th>
                 {{--  <th>Rol</th> --}}
                  <th>Acciones</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
   </div>
	</div>
@endsection

gestion-condominios/resources/views/admin/admins/type.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
	 <div class="row">
    <br><br><br>
    <center><p>Selecciona el tipo de administrador que vas a agregar</p></center>
    <br><br><br>
    <div class="frb-group">
    <div class="row">
        <div class="col-md-6">
            <div class="frb frb-info">
                  <input type="radio" id="radio-button-1" onclick="location.href='{{ route('admin.externAdmin') }}'" name="admin">
                <label for="radio-button-1">
                    <span class="frb-title">Administrador Externo</span>
                    <br>
                    <span class="frb-description">No vivo dentro del Conjunto Residencial. <br><br></span>
                </label>
            </div>
        </div>
        <div class="col-md-6">
            <div class="frb frb-info">
                <input type="radio" id="radio-button-2" onclick="location.href='{{ route('admin.internAdmin') }}'" name="admin">
                <label for="radio-button-2">
                    <span class="frb-title">Administrador Interno</span>
                    <br>
                    <span class="frb-description">Vivo dentro del Conjunto Residencial      </span>
                    <br><br>
                </label>
            </div>
        </div>
        <span class="form-control-feedback errors">{{ $errors->first('admin') }} </span>
    </div>
</div>
   </div>
	</div>

@endsection

gestion-condominios/resources/views/admin/banks-condominium/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
    <div class="row">
    <div class="col-md-9">
      <p></p>
    </div>
    <div class="col-md-3">
      <a href="{{ route('admin.banks-condominium.create') }}">
        <button class="btn btn-success btn-block" title="Agregar Banco"><i class="fa fa-plus"></i> Agregar Cuenta</button>
      </a>
    </div>
   </div>
   <br>
	 <div class="row">
      <div class="box box-info">
            <div class="box-header">
              <h3 class="box-title">Lista de Cuentas</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Banco</th>
                  <th>Nro. De Cuenta</th>
                  <th>Titular</th>
                  <th>Identificación</th>
                  <th>E-mail</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($banks as $bank)
                <tr>
                  <td>{{ $bank->name }}</td>
                  <td>{{ $bank->account_number }}</td>
                  <td>{{ $bank->holder }}</td>
                  <td>{{ $bank->dni }}</td>
                  <td>{{ $bank->email }}</td>
                  <td>
                    <center>
                    {!!link_to_route('admin.banks-condominium.edit', $title = ' Editar',
                                                    $parameters = ['id' => Crypt::encrypt($bank->id)],
                                                    $attributes = ['class'=>'btn btn-warning fa fa-edit']);!!}
                    <form style="display:inline" action="{{ route('admin.banks-condominium.destroy', $bank->id) }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('DELETE') !!}
                      <button type="submit" id="deleteButton" class="btn btn-danger"><span class="fa fa-trash" title="Eliminar"></span> Eliminar</button>
                    </form>
                    </center>
                  </td>
                </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Banco</th>
                  <th>Nro. De Cuenta</th>
                  <th>Titular</th>
                  <th>Identificación</th>
                  <th>E-mail</th>
                  <th>Acciones</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
   </div>
	</div>
@endsection

gestion-condominios/resources/views/admin/common-areas/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
    <div class="row">
    <div class="col-md-9">
      <p>Las áreas comunes son las áreas que comparten todos los habitantes del conjunto residencial, éstas pueden ser: Canchas, Piscinas, Parilleras, Parques, entre otros. <i>Por favor agrega las áreas comúnes para este conjunto residencial.</i></p>
    </div>
    <div class="col-md-3">
      <a href="{{ route('admin.common-areas.create') }}">
        <button class="btn btn-success btn-block" title="Agregar Área Común"><i class="fa fa-plus"></i> Agregar Área Común</button>
      </a>
    </div>
   </div>
   <br>
	 <div class="row">
      <div class="box box-info">
            <div class="box-header">
              <h3 class="box-title">Lista de Áreas Comunes</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                  @foreach($areas as $area)
                <tr>
                  <td>{{ $area->name }}</td>
                  <td>
                    {!!link_to_route('admin.common-areas.edit', $title = ' Editar',
                                                    $parameters = ['id' => Crypt::encrypt($area->id)],
                                                    $attributes = ['class'=>'btn btn-warning fa fa-edit']);!!}
                    <form style="display:inline" action="{{ route('admin.common-areas.destroy',$area->id) }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('DELETE') !!}
                      <button class="btn btn-danger"><span class="fa fa-trash" title="Eliminar"></span> Eliminar</button>
                    </form>
                  </td>
                </tr>
                  @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Nombre</th>
                  <th>Acciones</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
   </div>
	</div>
@endsection

gestion-condominios/resources/views/admin/defaulters/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
    <div class="row">
    <div class="col-md-9">
    </div>
    <div class="col-md-3">
      {{-- <a href="{{ route('admin.common-areas.create') }}">
        <button class="btn btn-success btn-block" title="Agregar Área Común"><i class="fa fa-plus"></i> Agregar Área Común</button>
      </a> --}}
    </div>
   </div>
   <br>
	 <div class="row">
      <div class="box box-info">
            <div class="box-header">
              <h3 class="box-title">Lista de Morosos</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Cédula</th>
                  <th>Nombre</th>
                  <th>Torre</th>
                  <th>Apartamento</th>
                  <th>Recibo en Mora</th>
                  <th>Mes</th>
                  <th>Mora Acumulada</th>
                </tr>
                </thead>
                <tbody>
                @foreach($defaulters as $defaulter)
                <tr>
                  <td>{{ $defaulter->ci }}</td>
                  <td>{{ $defaulter->name }} {{ $defaulter->last_name }}</td>
                  <td><center>{{ $defaulter->towerName }}</center></td>
                  <td><center>{{ $defaulter->floor }} - {{ $defaulter->apartment }}</center></td>
                  <td>#{{ $defaulter->nro }} - ({{ $defaulter->amount }} Bs)</td>
                  <td>{{ $defaulter->date->format('F Y') }}</td>
                  <td>{{ $defaulter->surcharge }} Bs</td>
                  {{-- <td>
                    {!!link_to_route('admin.common-areas.edit', $title = ' Editar',
                                                    $parameters = ['id' => Crypt::encrypt($area->id)],
                                                    $attributes = ['class'=>'btn btn-warning fa fa-edit']);!!}
                    <form style="display:inline" action="" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('DELETE') !!}
                      <button class="btn btn-danger"><span class="fa fa-trash" title="Eliminar"></span> Eliminar</button>
                    </form>
                  </td> --}}
                </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Cédula</th>
                  <th>Nombre</th>
                  <th>Torre</th>
                  <th>Apartamento</th>
                  <th>Recibo en Mora</th>
                  <th>Mes</th>
                  <th>Mora Acumulada</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
   </div>
	</div>
@endsection

gestion-condominios/resources/views/admin/owners/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
    <div class="row">
    <div class="col-md-9">
      <p></p>
    </div>
    <div class="col-md-3">
      <a href="{{ route('admin.owners.create') }}">
        <button class="btn btn-success btn-block" title="Agregar Propietario"><i class="fa fa-plus"></i> Agregar Propietario</button>
      </a>
    </div>
   </div>
   <br>
	 <div class="row">
      <div class="box box-info">
            <div class="box-header">
              <h3 class="box-title">Lista de Propietarios</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Nombre y Apellido</th>
                  <th>Correo</th>
                 {{--  <th>Teléfono</th> --}}
                  <th>Propietario de Apartamento(s)</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($owners as $owner)
                <tr>
                  <td>{{ $owner->name }} {{ $owner->last_name }}</td>
                  <td>{{ $owner->email }}</td>
                  {{-- <td>{{ $owner->number }}</td> --}}
                  <td>
                      {!! $owner->apartments_owner !!}
                    </td>
                  <td>
                    <center>
                    {!!link_to_route('admin.owners.edit', $title = ' Editar',
                                                    $parameters = ['id' => Crypt::encrypt($owner->id)],
                                                    $attributes = ['class'=>'btn btn-warning fa fa-edit']);!!}
                    <form style="display:inline" action="{{ route('admin.owners.destroy', $owner->id) }}" method="POST">
                        {!! csrf_field() !!}
                        {!! method_field('DELETE') !!}
                      <button type="submit" id="deleteButton" class="btn btn-danger"><span class="fa fa-trash" title="Eliminar"></span> Eliminar</button>
                    </form>
                    </center>
                  </td>
                </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Nombre y Apellido</th>
                  <th>Correo</th>
                  {{-- <th>Teléfono</th> --}}
                  <th>Propietario de Apartamento(s)</th>
                  <th>Acciones</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
   </div>
	</div>
@endsection

gestion-condominios/resources/views/admin/statistics/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection

@section('main-content')
	<div class="container-fluid spark-screen">
    <div class="row">
    <div class="col-md-12">
      <p></p>
    </div>
   <br>
	 <div class="row">
    <div class="container-fluid spark-screen">
    <div class="row">
      <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>{{ $cant_payments }}</h3>
            <p>Pagos Recibidos</p>
          </div>
          <div class="icon">
            <img height="80" width="80" src="{{ asset('img/fair.png') }}">
          </div>
          <a href="{{ route('admin.statistics.dateRange') }}" class="small-box-footer">Ver gráfico <i class="fa fa-arrow-circle-right"></i></a>
        </div>
       </div>
       <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>{{ $cant_expenses }}</h3>
            <p>Gastos</p>
          </div>
          <div class="icon">
            <img height="80" width="80" src="{{ asset('img/maintenance.png') }}">
          </div>
          <a href="{{ route('admin.statistics.typeExpense') }}" class="small-box-footer">Ver gráfico <i class="fa fa-arrow-circle-right"></i></a>
        </div>
       </div>
       <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>{{ $cant_owners }}</h3>
            <p>Propietarios</p>
          </div>
          <div class="icon">
            <img height="80" width="80" src="{{ asset('img/owner.png') }}">
          </div>
          <a href="{{ route('admin.owners.index') }}" class="small-box-footer">Ver Lista <i class="fa fa-arrow-circle-right"></i></a>
        </div>
       </div>
       <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>{{ $cant_defaulters }}</h3>

            <p>Morosos</p>
          </div>
          <div class="icon">
            <img height="80" width="80" src="{{ asset('img/owner.png') }}">
          </div>
          <a href="{{ route('admin.defaulters.index') }}" class="small-box-footer">Ver lista <i class="fa fa-arrow-circle-right"></i></a>
        </div>
       </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>{{ $acumulate_mora_round }} <small style="color: #FFF">Bs</small></h3>

            <p>Morosidad Acumulada</p>
          </div>
          <br>
          <div class="icon">
            <img height="80" width="80" src="{{ asset('img/fair.png') }}">
          </div>
          {{-- <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a> --}}
        </div>
       </div>
       <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>{{ $cant_admins }}</h3>

            <p>Administradores</p>
          </div>
          <div class="icon">
            <img height="80" width="80" src="{{ asset('img/comittee.png') }}">
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
       </div>

       <div class="col-lg-3 col-xs-6">
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>{{ $total_pays }} <small style="color: #FFF">Bs</small></h3>

            <p>Total Pagado</p>
          </div>
          <div class="icon">
            <img height="80" width="80" src="{{ asset('img/fair.png') }}">
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
       </div>
    </div>
    </div>
   </div>
	</div>
@endsection